---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ranslice.winlab.nycu
  resources:
  - oairanslice
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ranslice.winlab.nycu
  resources:
  - oairanslice/finalizers
  verbs:
  - update
- apiGroups:
  - ranslice.winlab.nycu
  resources:
  - oairanslice/status
  verbs:
  - get
  - patch
  - update
